#pragma once

#include <QJsonObject>
#include <QString>
#include <QVariantMap>
#include <QVector>

/**
 * @file ParserConfiguration.h
 * @brief Defines the serializable QtRecordParser configuration.
 */

namespace QtRecordParser
{
/**
 * @struct FieldConfiguration
 * @brief Describes one placeholder, capture pattern and converter.
 */
struct FieldConfiguration {
        QString id;
        QString display_name;
        QString capture_pattern{QStringLiteral(".*?")};
        QString converter_id{QStringLiteral("text")};
        QVariantMap converter_options;
        bool trim_value{false};
};

/**
 * @struct ParserConfiguration
 * @brief Describes a complete format-based parser configuration.
 *
 * The structure contains only serializable data and may therefore be created
 * by a settings UI, persisted as JSON or generated by an AI-assisted detector.
 */
struct ParserConfiguration {
        QString format;
        QVector<FieldConfiguration> fields;
        bool allow_unknown_fields{true};

        /**
         * @brief Converts the configuration to JSON.
         * @return Serializable JSON object.
         */
        [[nodiscard]] auto to_json() const -> QJsonObject;

        /**
         * @brief Creates a configuration from JSON.
         * @param object Serialized configuration.
         * @param error_message Receives validation or decoding errors.
         * @return Parsed configuration.
         */
        [[nodiscard]] static auto from_json(
            const QJsonObject& object, QString* error_message = nullptr) -> ParserConfiguration;
};
}  // namespace QtRecordParser
